<a href="https://colab.research.google.com/github/HFAJIR/GenAI_ML_Bootcamp/blob/main/Week5/Day1%20/Exercises_XP_Gold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Exercise 1 : Maximum Value Replacement in Matrix**

In [1]:
import numpy as np

# Create a random 5x5 matrix
A = np.random.rand(5, 5)
print("Original matrix:\n", A)

# Find the index of the maximum value
max_index = np.unravel_index(np.argmax(A), A.shape)

# Replace the maximum value with 0
A[max_index] = 0

print("\nMatrix after replacing max with 0:\n", np.round(A, 2))

Original matrix:
 [[0.95288297 0.25220696 0.40453474 0.43442804 0.02177767]
 [0.45392817 0.24880805 0.38428945 0.9334089  0.15350835]
 [0.53712743 0.98525473 0.62426926 0.56697161 0.81537831]
 [0.42603118 0.9652683  0.73898256 0.37123789 0.40033979]
 [0.76635401 0.77202163 0.14244571 0.38859219 0.9820602 ]]

Matrix after replacing max with 0:
 [[0.95 0.25 0.4  0.43 0.02]
 [0.45 0.25 0.38 0.93 0.15]
 [0.54 0.   0.62 0.57 0.82]
 [0.43 0.97 0.74 0.37 0.4 ]
 [0.77 0.77 0.14 0.39 0.98]]


# **Exercise 2 : Finding Common Values in Arrays**

In [ ]:
import numpy as np

# Create two random arrays of size 5
A = np.random.rand(5)
B = np.random.rand(5)
# Round values to 2 decimals
A = np.round(A, 2)
B = np.round(B, 2)

print("Array A:", A)
print("Array B:", B)

# Find common values (intersection)
common_values = np.intersect1d(A, B)

print("\nCommon values:\n", common_values)


Array A: [0.83 0.56 0.49 0.84 0.99]
Array B: [0.38 0.48 0.76 0.37 0.79]

Common values:
 []


# **Exercise 3 : Sorting Array in Ascending and Descending Order**

In [ ]:
import numpy as np

# Create a random 1D array of size 10
A = np.random.rand(10)
A = np.round(A, 2)
print("Original array:", A)

# Sort in ascending order
A_ascending = np.sort(A)
print("Ascending order:",A_ascending)

# Sort in descending order
A_descending = np.sort(A)[::-1]
print("Descending order:",A_descending)

Original array: [0.02 0.41 0.76 0.15 0.66 0.12 0.57 0.64 0.21 0.24]
Ascending order: [0.02 0.12 0.15 0.21 0.24 0.41 0.57 0.64 0.66 0.76]
Descending order: [0.76 0.66 0.64 0.57 0.41 0.24 0.21 0.15 0.12 0.02]


# **Exercise 4 : Matrix Rank Determination**

In [ ]:
matric_A = np.random.rand(4,4)
rank_A = np.linalg.matrix_rank(matric_A)
print("Matrix A:\n", matric_A)
print("\nRank of Matrix A:", rank_A)

Matrix A:
 [[0.00197727 0.59697463 0.9672076  0.48567978]
 [0.23551977 0.88485431 0.13850725 0.87146598]
 [0.12303492 0.35610626 0.95117139 0.39394375]
 [0.03957412 0.43830524 0.16527203 0.48356726]]

Rank of Matrix A: 4


# **Exercise 5 : Creating Border Array**

In [ ]:
import numpy as np

# Créer un tableau de zéros
array = np.zeros((5, 5), dtype=int)

# Mettre 1 sur les bords
array[0, :] = 1       # première ligne
array[-1, :] = 1      # dernière ligne
array[:, 0] = 1       # première colonne
array[:, -1] = 1      # dernière colonne


print(array)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
